### ISSUE TITLE
Add MD5 Checksum to Request Header and queryparameter

### ISSUE THREAD

**Issue by cutmasta-kun** [HalloTschuess/very-simple-upload-server#3]
It would be nice, if there were the possibility to pass a md5 checksum with the file.
The Client would need to calculate the md5 checksum for the file himself and add it to the request.
As soon as the header/queryparameter is present, the very-simple-upload-server would calculate the md5 checksum and compare with the given one from the request.

If the checksum isn't the same, the server could delete the file, because it may be corrupted or cut off.

That would be nice (. ❛ ᴗ ❛.)

**Comment by HalloTschuess** [comment]
Implemented with [Digest header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Digest) in version [1.3.0](https://github.com/HalloTschuess/very-simple-upload-server/releases/tag/1.3.0)
